export const SET_CURRENT_ONE_MENU_PATH = 'SET_CURRENT_ONE_MENU_PATH'
export const SET_CURRENT_TWO_MENU_PATH = 'SET_CURRENT_TWO_MENU_PATH'
export const RESET_FRAMEWORK_STATE = 'RESET_FRAMEWORK_STATE'